### ISSUE TITLE
Describe how many types of disturbances occur at the plot level

### ISSUE THREAD

**Issue by hupp2it** [nationalparkservice/mojn-iu-reporting#11]
It would be interesting to see if some plots have occurrences of many types of disturbance (e.g. 5 plots have more than 5 different types of disturbance), and to see how many plots had few or no types (e.g. 10 plots had no disturbance at all, wow!).

Not all these have to be done:
- [x] bar plot: x= total number of different disturbance classes, y= number of occurrences
- [x] stacked bar plot, y= percent cover (color by disturbance), x= plot ID (sorted by percent of "no disturbance", if possible)
- [ ] map with pie chart on each plot location breaking down disturbance by type

**Comment by wright13** [comment]
Skipping the pie chart map for now. It can be done (https://guangchuangyu.github.io/2016/12/scatterpie-for-plotting-pies-on-ggplot/) but there are enough disturbance categories that it would be hard to visualize without an interactive map that allows zooming in on pie charts.
