### ISSUE TITLE
View Disturbance by plot, not by point

### ISSUE THREAD

**Issue by hupp2it** [nationalparkservice/mojn-iu-reporting#4]
Change how disturbance data are portrayed-- they are currently bar charts showing type of disturbance by total frequency (over 3000 observations). We want presence/absence of a disturbance type at each macroplot. For example, 5 macroplots had disturbance by ants, 1 macroplot had undifferentiated disturbance (even though there were 25 observations at that macroplot).

LPI: 
- [x] Sort data by presence/absence of each type of disturbance at each plot (or perhaps there is a better method to do this)
- [x] Create figures to view type of disturbance by number of _plots_ where the disturbance occurs (~25 plots) 

Invasive Quadrats:
- [x] Sort data by presence/absence of each type of disturbance at each plot (or perhaps there is a better method to do this)
- [x] Create figures to view type of disturbance by number of _plots_ where the disturbance occurs (~25 plots)

**Comment by wright13** [comment]
Plots are basic but functional! Still need to decide on consistent look and feel and come up with a way to indicate total # of plots visited
