### ISSUE TITLE
Add functionality to set ylim for the LPI and quadrat disturbance figures

### ISSUE THREAD

**Issue by hupp2it** [nationalparkservice/mojn-iu-reporting#9]
The figures are hard to compare since they have different scales.

It would be nice to have another argument where we can set the ylim if desired, or it will default if that argument is left blank.

**Comment by wright13** [comment]
Done for all plots. Right now I'm using the expand_limits ggplot function to adjust ymax and ymin, which will expand limits past the default but won't cut stuff off if you specify values that fall inside the range of the data. I can't imagine a scenario where we would want to set y limits that cut off data, so I think it makes sense to do it this way? But it's trivial to change it if we do want that option.
